### ISSUE TITLE
Help Wanted: Guidance on Maven Package Metadata

### ISSUE THREAD

**Issue by kemitchell** [licensezero/cli#1]
The roadmap for this repo is currently:

- [x] Finish testing, release a 1.0.0, and update licensezero.com documentation to make this CLI the official client.
- [ ] Support Maven dependencies.

I would really appreciate advice on how to go about finding, reading, and writing License Zero metadata to Maven packages. I've done some Java and Clojure in the past, but it's not fresh in mind.

A few specific questions:

1. Is finding Maven dependencies in a Maven-based project as easy as recursing the project's filesystem hierarchy and reading `pom.xml` files?

2. Is the best approach shelling out to something like `mvn dependency:list`?

3. Should License Zero write licensing metadata to `pom.xml`? What's the cleanest, least-problematic way to do that? Should it write its own `licensezero.xml` or similar, instead?

4. Is it safe and idiomatic to write license terms to `LICENSE.txt` and `README` information to `README.txt`? That's documented as [standard directory layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html), but is it standard practice?

**Comment by kemitchell** [comment]
cc @eduardoejp

**Comment by kemitchell** [comment]
@eduardoejp, the latest here is that the CLI will inventory `licensezero.json` files wherever they appear in a project source tree. It will also try to find package manager metadata in the same directory, and report it to those who run `licensezero quote`, so they can sanity-check at a glance.

Current master reads any `pom.xml` in the same directory as any `licensezero.json` and attempts to read `artifactId`, `groupId`, and `version`.

**Comment by kemitchell** [comment]
A few open questions:

1. Does `licensezero license` have to do anything special to make sure `licensezero.json` is included in Maven packages? Is there a manifest file that `licensezero.json` should be added to?
2. It looks like it's common practice to have multiple `pom.xml` files in various subdirectories of a package. `licensezero quote` currently reads only the `pom.xml` found in the same directory as `licensezero.json`. Will that work?
3. Is it common to use Maven dependencies _outside_ the working directory of the project, say because they're installed system- or user-wide? If so, how do we list those dependencies, and find their paths?

**Comment by LuxLang** [comment]
Hey, @kemitchell 

Apologies for the delayed reply.
I've been a bit busy.

---

> 1. Is finding Maven dependencies in a Maven-based project as easy as recursing the project's filesystem hierarchy and reading pom.xml files?

Pretty much. It's a safe bet.

> 2. Is the best approach shelling out to something like mvn dependency:list?

I'd say so. It gives both direct and transitive dependencies, so it's a solid solution.

> 3. Should License Zero write licensing metadata to pom.xml? What's the cleanest, least-problematic way to do that? Should it write its own licensezero.xml or similar, instead?

It's better for L0 to have its own file, instead of writing to the POM or another build-tool-specific file.
Keeps things de-coupled. 

> 4. Is it safe and idiomatic to write license terms to LICENSE.txt and README information to README.txt? That's documented as standard directory layout, but is it standard practice?

It's probably safe. Those 2 files seem pretty ubiquitous (with the caveat that README.md is also common, due to GitHub's Markdown rendering).

> 1. Does licensezero license have to do anything special to make sure licensezero.json is included in Maven packages? Is there a manifest file that licensezero.json should be added to?

General Maven is not really my expertise, as I've only dealt with Maven indirectly through Clojure's Leiningen.
With that said, both Leiningen (and, I believe, Maven) package up the contents of `/resources` directories inside of `.jar` files that get generated.
This is often used for packaging assets, but `LICENSE` files often show up in `.jar` files.
Whether the `LICENSE` files were originally inside the `/resources` directory or not, I don't know.
But clearly there is a way to package arbitrary files, so I'd just leave the packaging duty to the programmers, so they handle it with their respective tools.

> 2. It looks like it's common practice to have multiple pom.xml files in various subdirectories of a package. licensezero quote currently reads only the pom.xml found in the same directory as licensezero.json. Will that work?

I'd advise to recursively check all the POM files.

> 3. Is it common to use Maven dependencies outside the working directory of the project, say because they're installed system- or user-wide? If so, how do we list those dependencies, and find their paths?

I'm not familiar with that use-case.
As far as I'm aware, dependencies will always be specified in the POM file, so it's probably safe to just rely on that.

**Comment by Nzen** [comment]
To be clear, I'm providing guidance without much understanding how developers use licensezero's cli . I've read through this and the corresponding python discussion, so I see understand two goals:

1. Provide an assessment of the licenses used by direct and transitive dependencies of this project
2. Ensure that using a typical build tool embeds the developer's licensezero.json file with the resulting artifact.

Another qualifier stems from my experience with maven and limited experience with gradle. While there are many other tools (buck, ant, and so on), snyk's 2020 jvm developer [survey results](https://snyk.io/wp-content/uploads/jvm_2020.pdf) show ~60-70% maven and ~20-30% gradle use among respondents.

That aside, for the first goal I recommend encouraging maven users to include codehaus' [license-maven-plugin](https://github.com/mojohaus/license-maven-plugin) as part of their build plugins. This checks for a license section in the pom of the direct and transitive dependencies and outputs a file called _THIRD-PARTY.txt_ in target/generated-sources/license of the project folder. 
[THIRD-PARTY.txt](https://github.com/licensezero/cli/files/4740918/THIRD-PARTY.txt) is a copy of the result from one of my projects. It showcases the formats used for typical licenses (ex MIT) as well as the output that results for dependencies that lack a license section (Unknown license, on the second line).

I use the following plugin configuration in my poms for license-maven-plugin:

```
	<plugin>
		<!-- Check license compatibility with dependencies -->
		<groupId>
			org.codehaus.mojo
			</groupId>
		<artifactId>
			license-maven-plugin
			</artifactId>
		<version>
			2.0.0
			</version>
		<executions>
			<execution>
				<id>
					affirm-other-licenses
					</id>
				<goals>
					<goal>
						add-third-party
						</goal>
					</goals>
				<configuration>
					<encoding>
						UTF-8
						</encoding>
					</configuration>
				</execution>
			</executions>
		</plugin>
```

For the second goal, adding licensezero.json as a project resource should be sufficient. Adding the following to a pom puts it at the root of the resulting artifact, assuming that file is in the root of the project folder (otherwise, substitute period with the relative path):

```
	<build>
		<resources>
			<resource>
				<directory>
					.
					</directory>
				<includes>
					<include>
						licensezero.json
						</include>
					</includes>
				</resource>
			</resources>
```

So, that's what I personally know. A quick search suggests there's a similar plugin for gradle, [gradle-license-report](https://github.com/jk1/Gradle-License-Report). It looks like adding a file to a gradle artifact involves [similarly specifying](https://stackoverflow.com/a/12413782/504994) the path to the resource for the jar task.

If I'm using licensezero to manage my license, overwriting my LICENSE file is fine. I consider it unwelcome for any tool to (parse and) overwrite the readme file of my project.

As to what licensezero-cli should do for maven-using developers in particular, I recommend suggesting the above maven plugin and parsing the output.

It could alternatively [drive maven](http://www.mojohaus.org/license-maven-plugin/plugin-info.html) to produce the list or (forfend) fork the project to change the output format to augment licensezero.json directly. If y'all aren't willing to expose licensezero-cli to a third party tool, then parsing `mvn dependency:list` and searching for the jars in ~/.m2/repository/ followed by the package path and so on. That won't find files in environments where the developer uses a remote repository (as we do at work) for downloading the artifacts. It is also possible for a developer to define a different folder for the local repository, in ~/.m2/settings.xml . That will have a section like `<localRepository>D:\some\other\root\.m2\repository</localRepository>` .

**Comment by kemitchell** [comment]
@nzen, thanks so much for this!
