### ISSUE TITLE
Help Wanted: NuGet Support

### ISSUE THREAD

**Issue by kemitchell** [licensezero/cli#33]
I'll have to admit: I've never used NuGet.  But I'd be chuffed to support it, and I think we have License Zero developers offering packages through the system.

Will NuGet project dependencies appear somewhere within the current working directory?

Is there a command I can shell out to, through the POSIX subsystem or WSL, that will list the patch of a project's dependencies?

If I find those paths, can I expect them to include `licensezero.json` files if the package developers included them?

**Comment by daveaglick** [comment]
You're in for a world of pain 😆 😬

First off, there really isn't a single NuGet tooling chain anymore. "Old-style" .NET projects rely on an out-of-band NuGet CLI with an external package definition file (similar to npm) while newer "SDK-style" .NET projects bake the dependencies directly into the project file. I'll focus on the latter since that's the way forward, but understand that doing so excludes some non-trivial amount of potential users.

With the newer NuGet tooling, the developer places the references directly into their project file (which is actually an MSBuild file - MSBuild is the build tool for .NET). The NuGet toolchain is built as a set of MSBuild extensions, so when the project is built, the NuGet extensions do the following:
- Query the NuGet gallery and other defined package sources for the package references specified in the project file
- Create a transitive closure of all packages directly and indirectly referenced, using some predefined rules to figure out specific versions (when to roll-forward, etc.)
- Add assembly references to the project for each package in the transitive closure, matching up platform and other constraints (many NuGet packages include assemblies for multiple platforms)

The important part for License Zero or any other tooling that needs to obtain a list of packages being used is that all the above happens at build time in memory. A conventional lock file doesn't get written and the developer isn't really intended to view the package closure. It's also important to note that because NuGet handles transitive dependencies, you can't just read the package references in the project file since the complete closure will be much, much larger after dependencies are resolved.

That said, there are hacks. If you force a build (I maintain a tool called [Buildalyzer](https://github.com/daveaglick/Buildalyzer) that can do this - it's surprisingly difficult to do programmatically), the NuGet MSBuild extensions actually do output a cache of all packages used by the project in a file typically called `project.assets.json`. You can then traverse the `project.assets.json` file to get the set of all packages used by the project. @mholo65 has written a great CLI tool called [Depends](https://github.com/mholo65/depends/blob/master/src/Depends.Core/DependencyAnalyzer.cs) that does exactly this so a developer can visualize their full transitive package closure. There's probably some code there that could be borrowed.

**Comment by daveaglick** [comment]
The previous comment was about how to figure out what packages are in use, but there's a whole other side of this which is figuring out which of those packages License Zero should care about and what their license terms are.

If the developer has added `licensezero.json` to the NuGet package, the file should be retrievable once you know which packages are in use and where they're located (NuGet caches package downloads globally by default so they won't be anywhere under the project folder like they are for npm). Assuming `licensezero.json` will get packed is a big assumption though - NuGet packages are a bit more opaque then npm packages and most developers don't manually pack anything. But since this is the early days, perhaps guidance could be provided on how to add the file to the package so it becomes a requirement if you want your L0-licensed package to be discoverable by the L0 CLI.

Most NuGet packages also include some metadata about the project repository. Another approach would be to use this metadata and then go query the repository directly for a `licensezero.json` file. That might add up to a lot of queries for a large dependency tree though.

All this said, I'm not sure the .NET community would rally behind a CLI tool that discovers license-able packages and offers to license them. At least not before a critical mass of such projects is likely to be included via package references. It's a wonderful ideal, but instead I would expect this particular community to just purchase licenses as-needed from the web interface. I'll ask @ghuntley for a reality check on this assumption though.

**Comment by kemitchell** [comment]
@daveaglick is the answer here that we provide some different tool, for installation in an IDE or otherwise within the build environment that understands the project files?

**Comment by daveaglick** [comment]
> is the answer here that we provide some different tool

Maybe, though my gut feeling is a CLI tool is still the best approach (delivery will make a difference - it should be available as a .NET global tool).

I'm certainly willing and eager to help get a NuGet capability off the ground, but I probably won't have much availability to do so until early next year.

**Comment by kemitchell** [comment]
> but I probably won't have much availability to do so until early next year.

Roger that. I am _not_ expecting you to do free work here, now or next year. I _really_ appreciate the high-level overview you found time to share here!

**Comment by bjorkstromm** [comment]
As the author of several NuGet integrations I might also be able to help. But having next to zero knowledge about License Zero and related tooling, I’d need some specs on how it should work. I just recently found out about License Zero through @daveaglick and I must admit I find it very interesting.

**Comment by kemitchell** [comment]
@mholo65, hello! L0's basic needs are:

1. Attach L0-specific metadata to NuGet packages.

2. Given the path of a project using NuGet, find all its NuGet dependencies that have L0-specific metadata, and collate that metadata.

**Comment by ghuntley** [comment]
> You're in for a world of pain 😆 😬

You're also in luck @zkat recently joined the NuGet team. 🎉 🎂

**Comment by daveaglick** [comment]
![DDF9243D-9E1A-4B0F-AD6F-4BDF68D697DB](https://user-images.githubusercontent.com/1020407/64665035-1dc47600-d41f-11e9-9c59-af3fc8aea5e5.gif)
