### ISSUE TITLE
Help Wanted: Guidance on RubyGems Package Metadata

### ISSUE THREAD

**Issue by kemitchell** [licensezero/cli#8]
Current master detects License Zero RubyGems by querying `bundle show` for package names and versions, then `bundle show $name` for path, then `$path/licensezero.json` to see if there's anything there. It will also pick up `licensezero.json` files in RubyGems within the working tree, but won't provide any package manager information, like name or version, for those packages.

Is it safe to assume most Ruby developers will have `bundle` on `$PATH`?

Is this the right approach to finding out what gems a project depends upon?

Given the path of an gem on disk---either installed globally or vendored, in the working tree---is there any reliable way to work backwards to package name and version?

**Comment by kemitchell** [comment]
An update here: Turns out, `bundle show` and `bundle show --path` sort their output by gem name, at least in the current version. So this CLI is running those commands and joining their output, rather than running `bundle show $name` for each gem.

**Comment by indirect** [comment]
It is pretty safe to assume that Ruby developers will have `bundle` in their path—it's so widely used that Ruby 2.5 almost included Bundler (but it didn't make it at the last minute). Whether Bundler ever ships with Ruby itself or not, Bundler has no competitors to speak of in the "application dependency management" space in Ruby. To be fair, you may be excluding a tiny number of developers who don't use Bundler because they don't write applications, and just use RubyGems directly to install packages that they call from scripts.

Because Bundler can include gems straight from any arbitrary path on disk, or from any arbitrary git repository, `bundle show --paths` can only tell you where to look on disk for a gem's files. The official way to get the gem's name and version is to use Ruby to evaluate the `gemspec` file, and read the name and version from that object. If you have a list of paths, that's probably something like:

```
$ export PATH_TO_GEM="/some/path/from/bundle/show"
$ ruby -rbundler -e "s=Bundler.load_gemspec Dir.glob('$PATH_TO_GEM/*.gemspec').first; puts s.name; puts s.version"
```

If you don't have Ruby available on the system you're running on... you may not have any way to extract the official name and version, because gemspecs can contain arbitrary Ruby code. 😬 For most gems (not including gems installed from git, or used directly from an arbitrary path on disk), you can get the official name and version directly from the path printed by `bundle show --paths`. Split the path on `/`, take only the last segment, then split on `-`. The version is the last item, the full name is every item but the last, rejoined with `-`.

Hope that helps.

**Comment by kemitchell** [comment]
@indirect, thanks so much for this!

At a high level, it sounds like `bundle show --paths` is in fact the answer to "What gems does the project at the current directory depend on?". That's a relief.

> To be fair, you may be excluding a tiny number of developers who don't use Bundler because they don't write applications, and just use RubyGems directly to install packages that they call from scripts.

Duly noted. This CLI's current approach _will_ catch gems committed into Git repositories. But it will not catch gems that merely happen to be `require`'d by a `.rb` in `$PWD`. But I think we can leave users in the situations you describe to handle license checking on their own.

> The official way to get the gem's name and version is to use Ruby to evaluate the gemspec file, and read the name and version from that object.

Thank you. I _thought_ this was the case, much as for `setup.py` in the Python world. But I think I've also seen some gems installed to my `/lib` _without_ the `.gemspec` in their directories. Perhaps that was a fluke.

> Split the path on /, take only the last segment, then split on -. The version is the last item, the full name is every item but the last, rejoined with -.

This was my initial approach. I moved later to running `bundle show` and parsing the output, which is very regular. I can find out for myself how `bundle` itself goes about finding those names.

---

Thanks again so much for this confirmation. Bundler has served long and well, and I used it for a number of past projects, but I wasn't confident in my current Ruby-fu.

Would you be alright with me thanking you on https://licensezero.com/thanks?

**Comment by indirect** [comment]
Great, I’m glad that was helpful! I’d be happy to be thanked. :)

As you might expect, Bundler gets the gem names and versions for `bundle show` by evaluating the gemspec files and then calling the name and version methods.

**Comment by kemitchell** [comment]
> I’d be happy to be thanked. :)

`thanks.json` is my favorite part of this project!

<https://licensezero.com/thanks>

> Bundler gets the gem names and versions for bundle show by evaluating the gemspec files and then calling the name and version methods.

Excellent!
